/**
 * Injury-site check boxes overlaid on the body figures of DD Form 1380 (JUL 2025),
 * extracted from the official fillable PDF. Coordinates are PDF points from the
 * page's top-left corner; labels are the form's own tooltips.
 */
export interface InjurySite {
  id: string;
  label: string;
  x: number;
  y: number;
  size: number;
}

export const ANTERIOR_SITES: readonly InjurySite[] = [
  { id: "Ant_Right_Shoulder", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Shoulder\"", x: 140.26, y: 271.41, size: 10.0 },
  { id: "Ant_Right_Lateral_Bicep", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Lateral Bicep\"", x: 137.31, y: 292.15, size: 10.0 },
  { id: "Ant_Right_Elbow", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Elbow\"", x: 137.17, y: 306.95, size: 10.0 },
  { id: "Ant_Right_Proximal_Lateral_Forearm", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Proximal Lateral Forearm\"", x: 133.79, y: 314.2, size: 10.0 },
  { id: "Ant_Right_Middle_Lateral_Forearm", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Middle Lateral Forearm\"", x: 130.41, y: 321.82, size: 10.0 },
  { id: "Ant_Right_Distal_Lateral_Forearm", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Distal Lateral Forearm\"", x: 127.77, y: 330.34, size: 10.0 },
  { id: "Ant_Right_Proximal_Medial_Forearm", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Proximal Medial Forearm\"", x: 140.53, y: 314.98, size: 10.0 },
  { id: "Ant_Right_Middle_Medial_Forearm", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Middle Medial Forearm\"", x: 136.96, y: 322.93, size: 10.0 },
  { id: "Ant_Right_Distal_Medial_Forearm", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Distal Medial Forearm\"", x: 134.14, y: 330.88, size: 10.0 },
  { id: "Ant_Right_Wrist", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Wrist\"", x: 128.94, y: 336.95, size: 10.0 },
  { id: "Right_Palm", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Palm\"", x: 127.43, y: 344.72, size: 10.0 },
  { id: "Ant_Right_Thumb", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Thumb\"", x: 118.54, y: 347.45, size: 10.0 },
  { id: "Ant_Right_Fingers", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Fingers\"", x: 126.22, y: 355.87, size: 10.0 },
  { id: "Ant_Right_Medial_Bicep", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Medial Bicep\"", x: 143.14, y: 298.04, size: 10.0 },
  { id: "AnteriorHead", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Head\"", x: 166.32, y: 236.34, size: 10.0 },
  { id: "Nose", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Nose\"", x: 167.88, y: 248.36, size: 8.0 },
  { id: "Mouth", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Mouth\"", x: 167.88, y: 253.84, size: 8.0 },
  { id: "Right_Eye", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Eye\"", x: 162.41, y: 244.01, size: 8.0 },
  { id: "Right_Ear", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Ear\"", x: 154.67, y: 246.84, size: 8.0 },
  { id: "Left_Ear", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Ear\"", x: 181.21, y: 246.84, size: 8.0 },
  { id: "Chin", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Chin\"", x: 167.88, y: 259.31, size: 8.0 },
  { id: "AnteriorNeck", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Anterior Neck\"", x: 167.88, y: 265.43, size: 8.0 },
  { id: "Left_Eye", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Eye\"", x: 173.47, y: 244.01, size: 8.0 },
  { id: "Right_Cheek", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Cheek\"", x: 161.72, y: 251.18, size: 8.0 },
  { id: "Left_Cheek", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Cheek\"", x: 173.47, y: 251.18, size: 8.0 },
  { id: "Right_Upper_Chest", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Upper Chest\"", x: 155.03, y: 271.69, size: 10.0 },
  { id: "Left_Upper_Chest", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Upper Chest\"", x: 178.18, y: 271.69, size: 10.0 },
  { id: "Sternum", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Sternum\"", x: 166.32, y: 290.27, size: 10.0 },
  { id: "RUQ", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Upper Quadrant\"", x: 156.48, y: 303.97, size: 10.0 },
  { id: "Right_Lower_Chest", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Lower Chest\"", x: 155.37, y: 287.73, size: 10.0 },
  { id: "LUQ", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Upper Quadrant\"", x: 174.46, y: 303.97, size: 10.0 },
  { id: "Left_Lower_Chest", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Lower Chest\"", x: 177.44, y: 287.73, size: 10.0 },
  { id: "Left_Axillary", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Axillary\"", x: 187.08, y: 286.12, size: 10.0 },
  { id: "Right_Axillary", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Axillary\"", x: 144.8, y: 286.12, size: 10.0 },
  { id: "RLQ", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Lower Quadrant\"", x: 158.7, y: 317.43, size: 10.0 },
  { id: "Right_Flank", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Flank\"", x: 149.53, y: 317.43, size: 10.0 },
  { id: "LLQ", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Lower Quadrant\"", x: 174.46, y: 317.43, size: 10.0 },
  { id: "Left_Flank", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Flank\"", x: 182.65, y: 317.43, size: 10.0 },
  { id: "Pelvis", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Pelvis\"", x: 166.32, y: 330.44, size: 10.0 },
  { id: "Right_Groin", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Groin\"", x: 156.7, y: 332.66, size: 10.0 },
  { id: "Left_Groin", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Groin\"", x: 174.84, y: 332.66, size: 10.0 },
  { id: "Right_Hip", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Hip\"", x: 147.81, y: 335.66, size: 10.0 },
  { id: "Left_Hip", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Hip\"", x: 184.1, y: 335.66, size: 10.0 },
  { id: "Genitals", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Genitals\"", x: 166.32, y: 349.6, size: 10.0 },
  { id: "Ant_Left_Shoulder", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Shoulder\"", x: 190.5, y: 271.41, size: 10.0 },
  { id: "Ant_Left_Lateral_Bicep", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Lateral Bicep\"", x: 196.16, y: 292.15, size: 10.0 },
  { id: "Ant_Left_Elbow", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Elbow\"", x: 194.89, y: 306.95, size: 10.0 },
  { id: "Ant_Left_Proximal_Lateral_Forearm", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Proximal Lateral Forearm\"", x: 200.46, y: 314.2, size: 10.0 },
  { id: "Ant_Left_Middle_Medial_Forearm", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Middle Medial Forearm\"", x: 195.96, y: 322.93, size: 10.0 },
  { id: "Ant_Left_Distal_Medial_Forearm", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Distal Medial Forearm\"", x: 199.72, y: 330.88, size: 10.0 },
  { id: "Ant_Left_Wrist", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Wrist\"", x: 204.64, y: 336.95, size: 10.0 },
  { id: "Left_Palm", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Palm\"", x: 205.37, y: 344.72, size: 10.0 },
  { id: "Ant_Left_Thumb", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Thumb\"", x: 214.84, y: 347.45, size: 10.0 },
  { id: "Ant_Left_Fingers", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Fingers\"", x: 205.78, y: 355.87, size: 10.0 },
  { id: "Ant_Left_Medial_Bicep", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Medial Bicep\"", x: 189.66, y: 298.04, size: 10.0 },
  { id: "Ant_Left_Middle_Lateral_Forearm", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Middle Lateral Forearm\"", x: 203.11, y: 321.82, size: 10.0 },
  { id: "Ant_Left_Distal_Lateral_Forearm", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Distal Lateral Forearm\"", x: 206.09, y: 330.34, size: 10.0 },
  { id: "Ant_Left_Proximal_Medial_Forearm", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Proximal Medial Forearm\"", x: 192.58, y: 314.98, size: 10.0 },
  { id: "Ant_Right_Middle_Lateral_Thigh", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Middle Lateral Thigh\"", x: 146.26, y: 355.48, size: 10.0 },
  { id: "Ant_Right_Proximal_Medial_Thigh", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Proximal Medial Thigh\"", x: 160.67, y: 350.41, size: 10.0 },
  { id: "Ant_Right_Middle_Medial_Thigh", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Middle Medial Thigh\"", x: 161.42, y: 359.47, size: 10.0 },
  { id: "Ant_Right_Knee", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Knee\"", x: 154.71, y: 384.16, size: 10.0 },
  { id: "Ant_Right_Proximal_Lateral_Lower_Leg", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Proximal Lateral Lower Leg\"", x: 150.47, y: 397.72, size: 10.0 },
  { id: "Ant_Right_Middle_Lateral_Lower_Leg", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Middle Lateral Lower Leg\"", x: 148.23, y: 409.8, size: 10.0 },
  { id: "Ant_Right_Distal_Lateral_Lower_Leg", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Distal Lateral Lower Leg\"", x: 152.18, y: 421.88, size: 10.0 },
  { id: "Ant_Right_Proximal_Medial_Lower_Leg", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Proximal Medial Lower Leg\"", x: 158.0, y: 397.72, size: 10.0 },
  { id: "Ant_Right_Middle_Medial_Lower_Leg", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Middle Medial Lower Leg\"", x: 157.24, y: 409.8, size: 10.0 },
  { id: "Ant_Right_Distal_Medial_Lower_Leg", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Distal Medial Lower Leg\"", x: 158.71, y: 421.88, size: 10.0 },
  { id: "Ant_Right_Ankle", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Ankle\"", x: 158.43, y: 432.6, size: 10.0 },
  { id: "Ant_Right_Foot", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Foot\"", x: 158.11, y: 440.7, size: 10.0 },
  { id: "Ant_Right_Big_Toe", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Big Toe\"", x: 161.61, y: 445.39, size: 10.0 },
  { id: "Ant_Right_Other_Toes", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Other Toes\"", x: 153.95, y: 446.29, size: 10.0 },
  { id: "Ant_Right_Distal_Lateral_Thigh", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Distal Lateral Thigh\"", x: 148.49, y: 369.27, size: 10.0 },
  { id: "Ant_Right_Distal_Medial_Thigh", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Distal Medial Thigh\"", x: 158.74, y: 369.27, size: 10.0 },
  { id: "Ant_Right_Proximal_Lateral_Thigh", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Right Proximal Lateral Thigh\"", x: 146.04, y: 341.69, size: 10.0 },
  { id: "Ant_Left_Middle_Lateral_Thigh", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Middle Lateral Thigh\"", x: 187.11, y: 355.67, size: 10.0 },
  { id: "Ant_Left_Proximal_Medial_Thigh", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Proximal Medial Thigh\"", x: 172.77, y: 350.41, size: 10.0 },
  { id: "Ant_Left_Middle_Medial_Thigh", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Middle Medial Thigh\"", x: 172.21, y: 359.47, size: 10.0 },
  { id: "Ant_Left_Knee", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Knee\"", x: 178.35, y: 384.73, size: 10.0 },
  { id: "Ant_Left_Proximal_Lateral_Lower_Leg", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Proximal Lateral Lower Leg \"", x: 184.07, y: 397.72, size: 10.0 },
  { id: "Ant_Left_Middle_Lateral_Lower_Leg", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Middle Lateral Lower Leg\"", x: 184.04, y: 409.8, size: 10.0 },
  { id: "Ant_Left_Distal_Lateral_Lower_Leg", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Distal Lateral Lower Leg\"", x: 181.36, y: 421.88, size: 10.0 },
  { id: "Ant_Left_Proximal_Medial_Lower_Leg", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Proximal Medial Lower Leg\"", x: 175.16, y: 397.72, size: 10.0 },
  { id: "Ant_Left_Middle_Medial_Lower_Leg", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Middle Medial Lower Leg\"", x: 175.16, y: 409.8, size: 10.0 },
  { id: "Ant_Left_Distal_Medial_Lower_Leg", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Distal Medial Lower Leg\"", x: 174.42, y: 421.88, size: 10.0 },
  { id: "Ant_Left_Ankle", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Ankle\"", x: 174.67, y: 432.6, size: 10.0 },
  { id: "Ant_Left_Foot", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Foot\"", x: 174.67, y: 440.7, size: 10.0 },
  { id: "Ant_Left_Big_Toe", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Big Toe\"", x: 170.0, y: 445.39, size: 10.0 },
  { id: "Ant_Left_Other_Toes", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Other Toes\"", x: 179.88, y: 446.29, size: 10.0 },
  { id: "Ant_Left_Distal_Lateral_Thigh", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Distal Lateral Thigh\"", x: 183.79, y: 369.64, size: 10.0 },
  { id: "Ant_Left_Distal_Medial_Thigh", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Distal Medial Thigh\"", x: 173.68, y: 369.27, size: 10.0 },
  { id: "Ant_Left_Proximal_Lateral_Thigh", label: "Injury: (Mark injuries with an X) - Anterior - Select for \"Left Proximal Lateral Thigh\"", x: 186.0, y: 341.69, size: 10.0 },
];

export const POSTERIOR_SITES: readonly InjurySite[] = [
  { id: "PosteriorHead", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Head\"", x: 339.68, y: 237.05, size: 10.0 },
  { id: "PosteriorNeck", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Neck\"", x: 339.68, y: 256.47, size: 10.0 },
  { id: "Thoracic_Spine", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Thoracic Spine\"", x: 339.68, y: 286.81, size: 10.0 },
  { id: "Lumbar_Spine", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Lumbar Spine\"", x: 339.68, y: 315.2, size: 10.0 },
  { id: "Left_Upper_Back", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Upper Back\"", x: 327.71, y: 271.11, size: 10.0 },
  { id: "Left_Middle_Back", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Middle Back\"", x: 327.71, y: 298.45, size: 10.0 },
  { id: "Left_Lower_Back", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Lower Back\"", x: 327.71, y: 319.82, size: 10.0 },
  { id: "Right_Upper_Back", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Upper Back\"", x: 351.65, y: 271.11, size: 10.0 },
  { id: "Right_Middle_Back", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Middle Back\"", x: 351.65, y: 298.45, size: 10.0 },
  { id: "Right_Lower_Back", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Lower Back\"", x: 351.65, y: 319.82, size: 10.0 },
  { id: "Tail_Bone", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Tail Bone\"", x: 339.68, y: 339.51, size: 10.0 },
  { id: "Left_Buttock", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Buttock\"", x: 326.98, y: 337.8, size: 10.0 },
  { id: "Right_Buttock", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Buttock\"", x: 352.39, y: 337.8, size: 10.0 },
  { id: "Post_Left_Shoulder", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Shoulder\"", x: 315.42, y: 272.58, size: 10.0 },
  { id: "Post_Left_Lateral_Bicep", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Lateral Bicep\"", x: 310.88, y: 289.99, size: 10.0 },
  { id: "Post_Left_Medial_Bicep", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Medial Bicep\"", x: 316.41, y: 297.27, size: 10.0 },
  { id: "Post_Left_Elbow", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Elbow\"", x: 311.61, y: 305.74, size: 10.0 },
  { id: "Post_Left_Proximal_Lateral_Forearm", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Proximal Lateral Forearm\"", x: 305.18, y: 311.57, size: 10.0 },
  { id: "Post_Left_Middle_Lateral_Forearm", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Middle Lateral Forearm\"", x: 302.61, y: 319.05, size: 10.0 },
  { id: "Post_Left_Distal_Lateral_Forearm", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Distal Lateral Forearm\"", x: 301.5, y: 326.52, size: 10.0 },
  { id: "Post_Left_Proximal_Medial_Forearm", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Proximal Medial Forearm\"", x: 313.18, y: 312.7, size: 10.0 },
  { id: "Post_Left_Middle_Medial_Forearm", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Middle Medial Forearm\"", x: 311.69, y: 320.15, size: 10.0 },
  { id: "Post_Left_Distal_Medial_Forearm", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Distal Medial Forearm\"", x: 307.99, y: 327.98, size: 10.0 },
  { id: "Post_Left_Wrist", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Wrist\"", x: 301.54, y: 333.99, size: 10.0 },
  { id: "Left_Hand", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Hand\"", x: 299.32, y: 343.8, size: 10.0 },
  { id: "Post_Left_Fingers", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Fingers\"", x: 297.05, y: 356.19, size: 10.0 },
  { id: "Post_Left_Thumb", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Thumb\"", x: 289.54, y: 347.94, size: 10.0 },
  { id: "Post_Right_Shoulder", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Shoulder\"", x: 363.36, y: 272.58, size: 10.0 },
  { id: "Post_Right_Lateral_Bicep", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Lateral Bicep\"", x: 368.75, y: 289.99, size: 10.0 },
  { id: "Post_Right_Medial_Bicep", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Medical Bicep\"", x: 363.47, y: 297.27, size: 10.0 },
  { id: "Post_Right_Elbow", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Elbow\"", x: 367.98, y: 306.48, size: 10.0 },
  { id: "Post_Right_Proximal_Lateral_Forearm", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Proximal Lateral Forearm\"", x: 374.02, y: 313.78, size: 10.0 },
  { id: "Post_Right_Middle_Lateral_Forearm", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Middle Lateral Forearm\"", x: 375.51, y: 321.29, size: 10.0 },
  { id: "Post_Right_Distal_Lateral_Forearm", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Distal Lateral Forearm\"", x: 378.11, y: 328.79, size: 10.0 },
  { id: "Post_Right_Proximal_Medial_Forearm", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Proximal Medial Forearm\"", x: 366.12, y: 314.92, size: 10.0 },
  { id: "Post_Right_Middle_Medial_Forearm", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Middle Medial Forearm\"", x: 369.1, y: 322.46, size: 10.0 },
  { id: "Post_Right_Distal_Medial_Forearm", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Distal Medial Forearm\"", x: 372.11, y: 330.69, size: 10.0 },
  { id: "Post_Right_Wrist", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Wrist\"", x: 378.1, y: 336.29, size: 10.0 },
  { id: "Right_Hand", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Hand\"", x: 378.88, y: 343.8, size: 10.0 },
  { id: "Post_Right_Thumb", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Thumb\"", x: 387.91, y: 347.94, size: 10.0 },
  { id: "Post_Right_Fingers", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Fingers\"", x: 380.0, y: 356.19, size: 10.0 },
  { id: "Post_Left_Proximal_Lateral_Thigh", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Proximal Lateral Thigh\"", x: 319.07, y: 352.43, size: 10.0 },
  { id: "Post_Left_Middle_Lateral_Thigh", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Middle Lateral Thigh\"", x: 322.02, y: 365.58, size: 10.0 },
  { id: "Post_Left_Distal_Lateral_Thigh", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Distal Lateral Thigh\"", x: 324.66, y: 378.72, size: 10.0 },
  { id: "Post_Left_Proximal_Medial_Thigh", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Proximal Medial Thigh\"", x: 334.57, y: 353.91, size: 10.0 },
  { id: "Post_Left_Middle_Medial_Thigh", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Middle Medial Thigh\"", x: 334.57, y: 365.58, size: 10.0 },
  { id: "Post_Left_Distal_Medial_Thigh", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Distal Medial Thigh\"", x: 333.09, y: 378.72, size: 10.0 },
  { id: "Post_Left_Knee", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Knee\"", x: 326.99, y: 388.97, size: 10.0 },
  { id: "Post_Left_Proximal_Lateral_Lower_Leg", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Proximal Lateral Lower Leg\"", x: 323.18, y: 399.75, size: 10.0 },
  { id: "Post_Left_Middle_Lateral_Lower_Leg", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Middle Lateral Lower Leg\"", x: 323.92, y: 412.57, size: 10.0 },
  { id: "Post_Left_Distal_Lateral_Lower_Leg", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Distal Lateral Lower Leg\"", x: 325.8, y: 426.12, size: 10.0 },
  { id: "Post_Left_Proximal_Medial_Lower_Leg", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Proximal Medial Lower Leg\"", x: 330.36, y: 399.75, size: 10.0 },
  { id: "Post_Left_Middle_Medial_Lower_Leg", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Middle Medial Lower Leg\"", x: 331.1, y: 412.57, size: 10.0 },
  { id: "Post_Left_Distal_Medial_Lower_Leg", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Distal Medial Lower Leg\"", x: 331.1, y: 426.12, size: 10.0 },
  { id: "Post_Left_Ankle", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Ankle\"", x: 331.03, y: 438.08, size: 10.0 },
  { id: "Left_Heel", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Left Heel\"", x: 331.03, y: 446.61, size: 10.0 },
  { id: "Post_Right_Proximal_Lateral_Thigh", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Lateral Proximal Thigh\"", x: 358.46, y: 352.43, size: 10.0 },
  { id: "Post_Right_Middle_Lateral_Thigh", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Middle Lateral Thigh\"", x: 356.25, y: 365.58, size: 10.0 },
  { id: "Post_Right_Distal_Lateral_Thigh", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Distal Lateral Thigh\"", x: 353.68, y: 378.72, size: 10.0 },
  { id: "Post_Right_Proximal_Medial_Thigh", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Proximal Medial Thigh\"", x: 344.98, y: 353.91, size: 10.0 },
  { id: "Post_Right_Middle_Medial_Thigh", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Middle Medial Thigh\"", x: 345.73, y: 365.58, size: 10.0 },
  { id: "Post_Right_Distal_Medial_Thigh", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Distal Medial Thigh\"", x: 346.73, y: 378.72, size: 10.0 },
  { id: "Post_Right_Knee", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Knee\"", x: 349.83, y: 388.97, size: 10.0 },
  { id: "Post_Right_Proximal_Lateral_Lower_Leg", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Proximal Lateral Lower Leg\"", x: 355.12, y: 399.75, size: 10.0 },
  { id: "Post_Right_Middle_Lateral_Lower_Leg", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Middle Lateral Lower Leg\"", x: 354.35, y: 412.57, size: 10.0 },
  { id: "Post_Right_Distal_Lateral_Lower_Leg", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Distal Lateral Lower Leg\"", x: 351.67, y: 426.12, size: 10.0 },
  { id: "Post_Right_Proximal_Medial_Lower_Leg", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Proximal Medial Lower Leg\"", x: 348.62, y: 399.75, size: 10.0 },
  { id: "Post_Right_Middle_Medial_Lower_Leg", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Middle Medial Lower Leg\"", x: 347.12, y: 412.57, size: 10.0 },
  { id: "Post_Right_Distal_Medial_Lower_Leg", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Distal Medial Lower Leg\"", x: 345.65, y: 426.12, size: 10.0 },
  { id: "Post_Right_Ankle", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Ankle\"", x: 346.49, y: 438.08, size: 10.0 },
  { id: "Right_Heel", label: "Injury: (Mark injuries with an X) - Posterior - Select for \"Right Heel\"", x: 346.49, y: 446.61, size: 10.0 },
];
