"use client";

import { useLocale, type Locale } from "@/i18n/locale";

/**
 * Printed labels only. Field names saved to Dexie stay the English PDF keys
 * in either language. Ukrainian follows the app locale code `uk`.
 */
const translations = {
  en: {
    sheetFront: "DD Form 1380 front",
    sheetBack: "DD Form 1380 back",
    title: "TACTICAL COMBAT CASUALTY CARE (TCCC) CARD",
    formNo: "DD FORM 1380, JUL 2025",
    formName: "TCCC CARD",
    roster: "BATTLE ROSTER #:",
    evac: "EVAC:",
    evacGroup: "EVAC",
    urgent: "Urgent",
    priority: "Priority",
    routine: "Routine",
    identity: "Casualty identity",
    name: "NAME (Last, First):",
    last4: "LAST 4:",
    sex: "SEX:",
    sexGroup: "SEX",
    male: "M",
    female: "F",
    date: "DATE",
    dateHint: "(DD-MMM-YY)",
    time: "TIME:",
    service: "SERVICE:",
    unit: "UNIT:",
    allergies: "ALLERGIES:",
    mechanism: "Mechanism of Injury",
    mechanismCap: "M",
    mechanismRest: "echanism of Injury: ",
    mechanismNote: "(X all that apply)",
    artillery: "Artillery",
    blunt: "Blunt",
    burn: "Burn",
    fall: "Fall",
    grenade: "Grenade",
    gsw: "GSW",
    ied: "IED",
    landmine: "Landmine",
    mvc: "MVC",
    rpg: "RPG",
    other: "Other",
    injury: "Injury",
    injuryCap: "I",
    injuryRest: "njury: ",
    injuryNote: "(Mark injuries with an X)",
    anterior: "Anterior",
    posterior: "Posterior",
    tq: "TQ:",
    rArm: "R Arm",
    lArm: "L Arm",
    rLeg: "R Leg",
    lLeg: "L Leg",
    type: "TYPE:",
    tqTime: "TIME:",
    vitals: "Signs & Symptoms",
    vitalsCap: "S",
    vitalsRest: "igns & Symptoms: ",
    vitalsNote: "(Fill in the blank)",
    timeCol: "Time",
    pulse: "Pulse (Rate & Location)",
    bp: "Blood Pressure",
    rr: "Respiratory Rate",
    o2: "Pulse Ox % O2 Sat",
    avpu: "AVPU",
    pain: "Pain Scale (0-10)",
    treatments: "Treatments",
    treatmentsCap: "T",
    treatmentsRest: "reatments: ",
    treatmentsNote: "(X all that apply, and fill in the blank)",
    typeCol: "Type",
    tqDash: "TQ-",
    extremity: "Extremity",
    junctional: "Junctional",
    truncal: "Truncal",
    dressingDash: "Dressing-",
    hemostatic: "Hemostatic",
    pressure: "Pressure",
    dressingOther: "Other",
    intact: "Intact",
    npa: "NPA",
    cric: "CRIC",
    etTube: "ET-Tube",
    sga: "SGA",
    o2tx: "O2",
    needle: "Needle-D",
    chestTube: "Chest-Tube",
    chestSeal: "Chest-Seal",
    fluids: "Circulation fluids and blood products",
    nameCol: "Name",
    volume: "Volume",
    route: "Route",
    timeHeader: "Time",
    fluid: "Fluid",
    blood: "Blood\nProduct",
    medsSection: "Medications",
    meds: "MEDS:",
    dose: "Dose",
    analgesic: "Analgesic",
    analgesicHint: "(e.g., Ketamine,\nFentanyl,\nMorphine)",
    antibiotic: "Antibiotic",
    antibioticHint: "(e.g., Moxifloxacin,\nErtapenem)",
    medsOther: "Other",
    medsOtherHint: "(e.g., TXA)",
    otherSection: "OTHER",
    otherLabel: "OTHER:",
    pillPack: "Combat-Pill-Pack",
    eye: "Eye-Shield (",
    eyeRight: "R",
    eyeLeft: "L",
    eyeClose: ")",
    splint: "Splint",
    hypothermia: "Hypothermia-Prevention",
    otherType: "Type:",
    notes: "NOTES",
    notesCap: "N",
    notesRest: "OTES:",
    responder: "First responder",
    responderLabel: "FIRST RESPONDER",
    responderName: "NAME (Last, First)",
    responderLast4: "LAST 4:",
  },
  uk: {
    sheetFront: "Лицьова сторона картки DD 1380",
    sheetBack: "Зворотна сторона картки DD 1380",
    title: "КАРТКА ПОРАНЕНОГО ТССС",
    formNo: "ФОРМА DD 1380, ЧЕРВЕНЬ 2014",
    formName: "КАРТКА ПОРАНЕНОГО ТССС",
    roster: "ОСОБИСТИЙ НОМЕР ВІЙСЬКОВОСЛУЖБОВЦЯ",
    evac: "ЕВАКУАЦІЯ:",
    evacGroup: "Евакуація",
    urgent: "НЕВІДКЛАДНА",
    priority: "ПРІОРИТЕТНА",
    routine: "ЗВИЧАЙНА",
    identity: "Особисті дані",
    name: "ПІБ (ПРІЗВИЩЕ, ІМ'Я)",
    last4: "ОСТАННІ 4 ЦИФРИ ІПН",
    sex: "СТАТЬ:",
    sexGroup: "Стать",
    male: "Ч",
    female: "Ж",
    date: "ДАТА",
    dateHint: "(ДД-ММ-РР)",
    time: "ЧАС:",
    service: "РІД ВІЙСЬК:",
    unit: "ПІДРОЗДІЛ:",
    allergies: "АЛЕРГІЯ:",
    mechanism: "Механізм поранення",
    mechanismCap: "М",
    mechanismRest: "ЕХАНІЗМ ПОРАНЕННЯ ",
    mechanismNote: "(позначте \"X\" все потрібне)",
    artillery: "Артобстріл",
    blunt: "Тупа травма",
    burn: "Опік",
    fall: "Падіння з висоти",
    grenade: "Граната",
    gsw: "Вогнепальна рана",
    ied: "СВП",
    landmine: "Протипіхотна міна",
    mvc: "ДТП",
    rpg: "РПГ",
    other: "Інше",
    injury: "Інформація про поранення",
    injuryCap: "",
    injuryRest: "Інформація про поранення ",
    injuryNote: "(позначте \"X\")",
    anterior: "Вид спереду",
    posterior: "Вид ззаду",
    tq: "Турнікет:",
    rArm: "Права рука",
    lArm: "Ліва рука",
    rLeg: "Права нога",
    lLeg: "Ліва нога",
    type: "Тип:",
    tqTime: "Час:",
    vitals: "Симптоми та ознаки",
    vitalsCap: "С",
    vitalsRest: "имптоми та ознаки ",
    vitalsNote: "(заповніть таблицю)",
    timeCol: "Час",
    pulse: "Пульс (частота та локалізація)",
    bp: "Артеріальний тиск",
    rr: "Частота дихання",
    o2: "Сатурація O2 %",
    avpu: "Рівень свідомості - AVPU",
    pain: "Шкала болю (0-10)",
    treatments: "Терапія",
    treatmentsCap: "Т",
    treatmentsRest: "ерапія/надана допомога: ",
    treatmentsNote: "(позначте \"X\" все, що потрібно та заповніть таблиці)",
    typeCol: "Тип",
    tqDash: "Турнікет -",
    extremity: "Для кінцівки",
    junctional: "Вузловий",
    truncal: "На тулуб",
    dressingDash: "Пов'язка -",
    hemostatic: "Гемостатична",
    pressure: "Тиснуча",
    dressingOther: "Інша",
    intact: "Неушкоджені",
    npa: "Назофарингеальний повітровід",
    cric: "Крікотиреотомія",
    etTube: "Ендотрахеальна трубка",
    sga: "Надгортанний повітровід",
    o2tx: "O2",
    needle: "Голкова декомпресія",
    chestTube: "Дренаж",
    chestSeal: "Оклюзійна наліпка",
    fluids: "Рідина та продукт крові",
    nameCol: "Назва",
    volume: "Об'єм",
    route: "Шлях\nвведення",
    timeHeader: "Час",
    fluid: "Рідина",
    blood: "Продукт\nкрові",
    medsSection: "Медикаменти",
    meds: "Медикаменти:",
    dose: "Дозування",
    analgesic: "Анальгетик",
    analgesicHint: "(напр., кетамін,\nфентаніл)",
    antibiotic: "Антибіотик",
    antibioticHint: "(напр.,\nмоксифлоксацин,\nертапенем)",
    medsOther: "Інше",
    medsOtherHint: "(напр., TXA)",
    otherSection: "Інше",
    otherLabel: "ІНШЕ:",
    pillPack: "Ліки з Військового набору таблеток для лікування ран",
    eye: "Щиток на око (",
    eyeRight: "праве",
    eyeLeft: "ліве",
    eyeClose: ")",
    splint: "Шина",
    hypothermia: "Метод попередження гіпотермії",
    otherType: "Тип:",
    notes: "Нотатки",
    notesCap: "Н",
    notesRest: "ОТАТКИ:",
    responder: "Рятувальник",
    responderLabel: "РЯТУВАЛЬНИК:",
    responderName: "ПІБ (Прізвище, Ім'я)",
    responderLast4: "ОСТАННІ 4 ЦИФРИ ІПН:",
  },
} as const satisfies Record<Locale, Record<string, string>>;

export type CardCopy = (typeof translations)[Locale];

export function cardCopy(locale: Locale): CardCopy {
  return translations[locale];
}

/** Follows the locale stored by Settings (`en` | `uk`). */
export function useCardCopy(): CardCopy {
  return translations[useLocale()];
}

export { translations };
