/** Tooltips of the official DD Form 1380 fillable PDF, keyed by its field names. */
export const FIELD_TIPS: Readonly<Record<string, string>> = {
  roster: "BATTLE ROSTER NUMBER:",
  evac_urgent: "EVACUATION - Select for \"Urgent\"",
  evac_priority: "EVACUATION - Select for \"Priority\"",
  evac_routine: "EVACUATION - Select for \"Routine\"",
  name: "NAME (Last, First):",
  last4: "LAST 4 DIGITS OF SOCIAL SECURITY NUMBER:",
  male: "SEX - Select for \"Male\"",
  female: "SEX - Select for \"Female\"",
  date: "DATE (DD-MMM-YY):",
  time: "TIME:",
  service: "SERVICE:",
  unit: "UNIT:",
  allergies: "ALLERGIES:",
  mechanism_artillery: "Mechanism of Injury: (X all that apply) - Select for \"Artillery\"",
  mechanism_blunt: "Mechanism of Injury: (X all that apply) - Select for \"Blunt\"",
  mechanism_burn: "Mechanism of Injury: (X all that apply) - Select for \"Burn\"",
  mechanism_fall: "Mechanism of Injury: (X all that apply) - Select for \"Fall\"",
  mechanism_grenade: "Mechanism of Injury: (X all that apply) - Select for \"Grenade\"",
  mechanism_gsw: "Mechanism of Injury: (X all that apply) - Select for \"Gunshot Wound\"",
  mechanism_ied: "Mechanism of Injury: (X all that apply) - Select for \"improvised explosive device\"",
  mechanism_landmine: "Mechanism of Injury: (X all that apply) - Select for \"Landmine\"",
  mechanism_mvc: "Mechanism of Injury: (X all that apply) - Select for \"motor vehicle crash/collision\"",
  mechanism_rpg: "Mechanism of Injury: (X all that apply) - Select for \"rocket-propelled grenade\"",
  mechanism_other: "Mechanism of Injury: (X all that apply) - Select for \"Other\"",
  mechanism_specify: "Mechanism of Injury - enter specification for \"Other\"",
  r_arm_type: "Injury - If a tourniquet is applied to the right arm, write type of tourniquet used.",
  r_arm_time: "Injury - If a tourniquet is applied to the right arm, write time of tourniquet application.",
  r_leg_type: "Injury - If a tourniquet is applied to the right leg, write type of tourniquet used.",
  r_leg_time: "Injury - If a tourniquet is applied to the right leg, write time of tourniquet application.",
  l_arm_type: "Injury - If a tourniquet is applied to the left arm, write type of tourniquet used.",
  l_arm_time: "Injury - If a tourniquet is applied to the left arm, write time of tourniquet application.",
  l_leg_type: "Injury - If a tourniquet is applied to the left leg, write type of tourniquet used.",
  l_leg_time: "Injury - If a tourniquet is applied to the left leg, write time of tourniquet application.",
  time1: "Signs & Symptoms: (Fill in the blank) - Time, column 1",
  time2: "Signs & Symptoms: (Fill in the blank) - Time, column 2",
  time3: "Signs & Symptoms: (Fill in the blank) - Time, column 3",
  time4: "Signs & Symptoms: (Fill in the blank) - Time, column 4",
  pulse1: "Signs & Symptoms: (Fill in the blank) - Pulse (Rate & Location), column 1",
  pulse2: "Signs & Symptoms: (Fill in the blank) - Pulse (Rate & Location), column 2",
  pulse3: "Signs & Symptoms: (Fill in the blank) - Pulse (Rate & Location), column 3",
  pulse4: "Signs & Symptoms: (Fill in the blank) - Pulse (Rate & Location), column 4",
  bloodPressureA1: "Signs & Symptoms: (Fill in the blank) - Blood Pressure (enter top number for the systolic pressure), column 1",
  bloodPressureB1: "Signs & Symptoms: (Fill in the blank) - Blood Pressure (enter bottom number for the diastolic pressure), column 1",
  bloodPressureA2: "Signs & Symptoms: (Fill in the blank) - Blood Pressure (enter top number for the systolic pressure), column 2",
  bloodPressureB2: "Signs & Symptoms: (Fill in the blank) - Blood Pressure (enter bottom number for the diastolic pressure), column 2",
  bloodPressureA3: "Signs & Symptoms: (Fill in the blank) - Blood Pressure (enter top number for the systolic pressure), column 3",
  bloodPressureB3: "Signs & Symptoms: (Fill in the blank) - Blood Pressure (enter bottom number for the diastolic pressure), column 3",
  bloodPressureA4: "Signs & Symptoms: (Fill in the blank) - Blood Pressure (enter top number for the systolic pressure), column 4",
  bloodPressureB4: "Signs & Symptoms: (Fill in the blank) - Blood Pressure (enter bottom number for the diastolic pressure), column 4",
  respRate1: "Signs & Symptoms: (Fill in the blank) - Respiratory Rate, column 1",
  respRate2: "Signs & Symptoms: (Fill in the blank) - Respiratory Rate, column 2",
  respRate3: "Signs & Symptoms: (Fill in the blank) - Respiratory Rate, column 3",
  respRate4: "Signs & Symptoms: (Fill in the blank) - Respiratory Rate, column 4",
  o2sat1: "Signs & Symptoms: (Fill in the blank) - Oxygen Saturation, column 1",
  o2sat2: "Signs & Symptoms: (Fill in the blank) - Oxygen Saturation, column 2",
  o2sat3: "Signs & Symptoms: (Fill in the blank) - Oxygen Saturation, column 3",
  o2sat4: "Signs & Symptoms: (Fill in the blank) - Oxygen Saturation, column 4",
  avpu1: "Signs & Symptoms: (Fill in the blank) - AVPU (Level of consciousness: A = Alert, V = responds to Verbal stimulus, P = responds to Pain stimulus, U = Unresponsive), column 1 (select from drop-down list)",
  avpu2: "Signs & Symptoms: (Fill in the blank) - AVPU (Level of consciousness: A = Alert, V = responds to Verbal stimulus, P = responds to Pain stimulus, U = Unresponsive), column 2 (select from drop-down list)",
  avpu3: "Signs & Symptoms: (Fill in the blank) - AVPU (Level of consciousness: A = Alert, V = responds to Verbal stimulus, P = responds to Pain stimulus, U = Unresponsive), column 3 (select from drop-down list)",
  avpu4: "Signs & Symptoms: (Fill in the blank) - AVPU (Level of consciousness: A = Alert, V = responds to Verbal stimulus, P = responds to Pain stimulus, U = Unresponsive), column 4 (select from drop-down list)",
  pain1: "Signs & Symptoms: (Fill in the blank) - Pain Scale (0 to 10), column 1 (select from drop-down list)",
  pain2: "Signs & Symptoms: (Fill in the blank) - Pain Scale (0 to 10), column 2 (select from drop-down list)",
  pain3: "Signs & Symptoms: (Fill in the blank) - Pain Scale (0 to 10), column 3 (select from drop-down list)",
  pain4: "Signs & Symptoms: (Fill in the blank) - Pain Scale (0 to 10), column 4 (select from drop-down list)",
  treatment_C_TQ_Extremity: "Treatments: (X all that apply, and fill in the blank) - Circulation hemorrhage control interventions - Tourniquet - Select for \"Extremity\"",
  treatment_C_TQ_Junctional: "Treatments: (X all that apply, and fill in the blank) - Circulation hemorrhage control interventions - Tourniquet - Select for \"Junctional\"",
  treatment_C_TQ_Truncal: "Treatments: (X all that apply, and fill in the blank) - Circulation hemorrhage control interventions - Tourniquet - Select for \"Truncal\"",
  treatment_C_TQ_type: "Treatments: (X all that apply, and fill in the blank) - Circulation hemorrhage control interventions - enter type of tourniquet(s) used",
  treatment_C_Dressing_Hemostatic: "Treatments: (X all that apply, and fill in the blank) - Circulation hemorrhage control interventions - Dressing - Select for \"Hemostatic\"",
  treatment_C_Dressing_Pressure: "Treatments: (X all that apply, and fill in the blank) - Circulation hemorrhage control interventions - Dressing - Select for \"Pressure\"",
  treatment_C_Dressing_Other: "Treatments: (X all that apply, and fill in the blank) - Circulation hemorrhage control interventions - Dressing - Select for \"Other\"",
  treatment_C_Dressing_type: "Treatments: (X all that apply, and fill in the blank) - Circulation hemorrhage control interventions - Dressing - enter type of dressing(s) used",
  treatment_A_Intact: "Treatments: (X all that apply, and fill in the blank) - Airway interventions - Select for \"Intact\"",
  treatment_A_NPA: "Treatments: (X all that apply, and fill in the blank) - Airway interventions - Select for \"nasopharyngeal airway\"",
  treatment_A_CRIC: "Treatments: (X all that apply, and fill in the blank) - Airway interventions - Select for \"cricothyroidotomy\"",
  "treatment_A_ET-Tube": "Treatments: (X all that apply, and fill in the blank) - Airway interventions - Select for \"endotracheal tube\"",
  treatment_A_SGA: "Treatments: (X all that apply, and fill in the blank) - Airway interventions - Select for \"supraglottic airway\"",
  treatment_A_type: "Treatments: (X all that apply, and fill in the blank) - Airway interventions - enter type of device(s) used",
  treatment_B_O2: "Treatments: (X all that apply, and fill in the blank) - Breathing interventions - Select for \"oxygen\"",
  treatment_B_NeedleD: "Treatments: (X all that apply, and fill in the blank) - Breathing interventions - Select for \"needle decompression\"",
  "treatment_B_Chest-Tube": "Treatments: (X all that apply, and fill in the blank) - Breathing interventions - Select for \"Chest-Tube\"",
  treatment_B_ChestSeal: "Treatments: (X all that apply, and fill in the blank) - Breathing interventions - Select for \"Chest-Seal\"",
  treatment_B_type: "Treatments: (X all that apply, and fill in the blank) - Breathing interventions - enter type of device(s) used",
  treatment_C_Fluid_Name1: "Treatments: (X all that apply, and fill in the blank) - Circulation resuscitation interventions - Fluid - Name, line 1",
  treatment_C_Fluid_Volume1: "Treatments: (X all that apply, and fill in the blank) - Circulation resuscitation interventions - Fluid - Volume, line 1",
  treatment_C_Fluid_Route1: "Treatments: (X all that apply, and fill in the blank) - Circulation resuscitation interventions - Fluid - Route, line 1",
  treatment_C_Fluid_Time1: "Treatments: (X all that apply, and fill in the blank) - Circulation resuscitation interventions - Fluid - Time, line 1",
  treatment_C_Fluid_Name2: "Treatments: (X all that apply, and fill in the blank) - Circulation resuscitation interventions - Fluid - Name, line 2",
  treatment_C_Fluid_Volume2: "Treatments: (X all that apply, and fill in the blank) - Circulation resuscitation interventions - Fluid - Volume, line 2",
  treatment_C_Fluid_Route2: "Treatments: (X all that apply, and fill in the blank) - Circulation resuscitation interventions - Fluid - Route, line 2",
  treatment_C_Fluid_Time2: "Treatments: (X all that apply, and fill in the blank) - Circulation resuscitation interventions - Fluid - Time, line 2",
  treatment_C_BloodProduct_Name1: "Treatments: (X all that apply, and fill in the blank) - Circulation resuscitation interventions - Blood Product - Name, line 1",
  treatment_C_BloodProduct_Volume1: "Treatments: (X all that apply, and fill in the blank) - Circulation resuscitation interventions - Blood Product - Volume, line 1",
  treatment_C_BloodProduct_Route1: "Treatments: (X all that apply, and fill in the blank) - Circulation resuscitation interventions - Blood Product - Route, line 1",
  treatment_C_BloodProduct_Time1: "Treatments: (X all that apply, and fill in the blank) - Circulation resuscitation interventions - Blood Product - Time, line 1",
  treatment_C_BloodProduct_Name2: "Treatments: (X all that apply, and fill in the blank) - Circulation resuscitation interventions - Blood Product - Name, line 2",
  treatment_C_BloodProduct_Volume2: "Treatments: (X all that apply, and fill in the blank) - Circulation resuscitation interventions - Blood Product - Volume, line 2",
  treatment_C_BloodProduct_Route2: "Treatments: (X all that apply, and fill in the blank) - Circulation resuscitation interventions - Blood Product - Route, line 2",
  treatment_C_BloodProduct_Time2: "Treatments: (X all that apply, and fill in the blank) - Circulation resuscitation interventions - Blood Product - Time, line 2",
  treatment_MEDS_Analgesic_Name1: "Treatments: (X all that apply, and fill in the blank) - Medications - Analgesic (e.g., Ketamine, Fentanyl, Morphine) - Name, line 1",
  treatment_MEDS_Analgesic_Dose1: "Treatments: (X all that apply, and fill in the blank) - Medications - Analgesic (e.g., Ketamine, Fentanyl, Morphine) - Dose, line 1",
  treatment_MEDS_Analgesic_Route1: "Treatments: (X all that apply, and fill in the blank) - Medications - Analgesic (e.g., Ketamine, Fentanyl, Morphine) - Route, line 1",
  treatment_MEDS_Analgesic_Time1: "Treatments: (X all that apply, and fill in the blank) - Medications - Analgesic (e.g., Ketamine, Fentanyl, Morphine) - Time, line 1",
  treatment_MEDS_Analgesic_Name2: "Treatments: (X all that apply, and fill in the blank) - Medications - Analgesic (e.g., Ketamine, Fentanyl, Morphine) - Name, line 2",
  treatment_MEDS_Analgesic_Dose2: "Treatments: (X all that apply, and fill in the blank) - Medications - Analgesic (e.g., Ketamine, Fentanyl, Morphine) - Dose, line 2",
  treatment_MEDS_Analgesic_Route2: "Treatments: (X all that apply, and fill in the blank) - Medications - Analgesic (e.g., Ketamine, Fentanyl, Morphine) - Route, line 2",
  treatment_MEDS_Analgesic_Time2: "Treatments: (X all that apply, and fill in the blank) - Medications - Analgesic (e.g., Ketamine, Fentanyl, Morphine) - Time, line 2",
  treatment_MEDS_Analgesic_Name3: "Treatments: (X all that apply, and fill in the blank) - Medications - Analgesic (e.g., Ketamine, Fentanyl, Morphine) - Name, line 3",
  treatment_MEDS_Analgesic_Dose3: "Treatments: (X all that apply, and fill in the blank) - Medications - Analgesic (e.g., Ketamine, Fentanyl, Morphine) - Dose, line 3",
  treatment_MEDS_Analgesic_Route3: "Treatments: (X all that apply, and fill in the blank) - Medications - Analgesic (e.g., Ketamine, Fentanyl, Morphine) - Route, line 3",
  treatment_MEDS_Analgesic_Time3: "Treatments: (X all that apply, and fill in the blank) - Medications - Analgesic (e.g., Ketamine, Fentanyl, Morphine) - Time, line 3",
  treatment_MEDS_Antibiotic_Name1: "Treatments: (X all that apply, and fill in the blank) - Medications - Antibiotic (e.g., Moxifloxacin, Ertapenem) - Name, line 1",
  treatment_MEDS_Antibiotic_Dose1: "Treatments: (X all that apply, and fill in the blank) - Medications - Antibiotic (e.g., Moxifloxacin, Ertapenem) - Dose, line 1",
  treatment_MEDS_Antibiotic_Route1: "Treatments: (X all that apply, and fill in the blank) - Medications - Antibiotic (e.g., Moxifloxacin, Ertapenem) - Route, line 1",
  treatment_MEDS_Antibiotic_Time1: "Treatments: (X all that apply, and fill in the blank) - Medications - Antibiotic (e.g., Moxifloxacin, Ertapenem) - Time, line 1",
  treatment_MEDS_Antibiotic_Name2: "Treatments: (X all that apply, and fill in the blank) - Medications - Antibiotic (e.g., Moxifloxacin, Ertapenem) - Name, line 2",
  treatment_MEDS_Antibiotic_Dose2: "Treatments: (X all that apply, and fill in the blank) - Medications - Antibiotic (e.g., Moxifloxacin, Ertapenem) - Dose, line 2",
  treatment_MEDS_Antibiotic_Route2: "Treatments: (X all that apply, and fill in the blank) - Medications - Antibiotic (e.g., Moxifloxacin, Ertapenem) - Route, line 2",
  treatment_MEDS_Antibiotic_Time2: "Treatments: (X all that apply, and fill in the blank) - Medications - Antibiotic (e.g., Moxifloxacin, Ertapenem) - Time, line 2",
  treatment_MEDS_Other_Name1: "Treatments: (X all that apply, and fill in the blank) - Medications - Other (e.g., TXA) - Name, line 1",
  treatment_MEDS_Other_Dose1: "Treatments: (X all that apply, and fill in the blank) - Medications - Other (e.g., TXA) - Dose, line 1",
  treatment_MEDS_Other_Route1: "Treatments: (X all that apply, and fill in the blank) - Medications - Other (e.g., TXA) - Route, line 1",
  treatment_MEDS_Other_Time1: "Treatments: (X all that apply, and fill in the blank) - Medications - Other (e.g., TXA) - Time, line 1",
  treatment_MEDS_Other_Name2: "Treatments: (X all that apply, and fill in the blank) - Medications - Other (e.g., TXA) - Name, line 2",
  treatment_MEDS_Other_Dose2: "Treatments: (X all that apply, and fill in the blank) - Medications - Other (e.g., TXA) - Dose, line 2",
  treatment_MEDS_Other_Route2: "Treatments: (X all that apply, and fill in the blank) - Medications - Other (e.g., TXA) - Route, line 2",
  treatment_MEDS_Other_Time2: "Treatments: (X all that apply, and fill in the blank) - Medications - Other (e.g., TXA) - Time, line 2",
  treatment_other_CombatPillPack: "Treatments: (X all that apply, and fill in the blank) - OTHER - Select for \"Combat-Pill-Pack\"",
  treatment_other_EyeShield: "Treatments: (X all that apply, and fill in the blank) - OTHER - Select for \"Eye-Shield\"",
  treatment_other_R: "Treatments: (X all that apply, and fill in the blank) - OTHER - Eye-Shield - Select for \"Right\"",
  treatment_other_L: "Treatments: (X all that apply, and fill in the blank) - OTHER - Eye-Shield - Select for \"Left\"",
  treatment_other_Splint: "Treatments: (X all that apply, and fill in the blank) - OTHER - Select for \"Splint\"",
  treatment_other_HypothermiaPrevention: "Treatments: (X all that apply, and fill in the blank) - OTHER - Select for \"Hypothermia-Prevention\"",
  treatment_other_type: "Treatments: (X all that apply, and fill in the blank) - OTHER - enter type of device(s) used",
  firstResponder_name: "FIRST RESPONDER - NAME (Last, First):",
  firstResponder_last4: "FIRST RESPONDER - LAST 4 DIGITS OF SOCIAL SECURITY NUMBER:",
};
